name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v4

      - name: ⏬ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⏬ Install
        run: |
          npm install
          cd playground
          npm install

      - name: ✨ Lint
        run: |
          npm run lint

      - name: 🔨 Build
        run: |
          npm run build

      - name: 🔨 Build Playground
        run: |
          cd playground
          npm run build

      - name: 🧪 Test
        run: |
          npm test
        env:
          FORCE_COLOR: 1

      - name: 📦 Publish
        if: ${{ github.ref == 'refs/heads/main' && matrix['node-version'] == '20.x' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm run trypublish
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: 📦 Deploy Playground
        if: ${{ github.ref == 'refs/heads/main' && matrix['node-version'] == '20.x' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: playground/dist
